### ISSUE TITLE
How about add the github action

### ISSUE THREAD

**Issue by lindexi** [wjk/dotnet-wpf#4] opened 2021-01-05 03:56 UTC
I use github action to build and publish my self wpf. And I think it is usefully.

See: https://github.com/dotnet-campus/wpf/pulls

**Comment by wjk** [comment] 2021-01-05 18:56
[I'm currently working on that](https://github.com/wjk/dotnet-wpf/tree/main/.github/workflows). I have not yet gotten this repo to build cleanly in CI, and I cannot test CD until after that. If you'd like something that you can work on immediately, you can look into why the CI build for #1 is failing. It complains of missing symbols when linking WpfGfx; I suspect the cause to be a race condition in the build sequence, as the list of missing symbols is different every time. The other two currently open PRs need code fixes. Thanks!

**Comment by lindexi** [comment] 2021-01-09 01:04
> 
> 
> [I'm currently working on that](https://github.com/wjk/dotnet-wpf/tree/main/.github/workflows). I have not yet gotten this repo to build cleanly in CI, and I cannot test CD until after that. If you'd like something that you can work on immediately, you can look into why the CI build for #1 is failing. It complains of missing symbols when linking WpfGfx; I suspect the cause to be a race condition in the build sequence, as the list of missing symbols is different every time. The other two currently open PRs need code fixes. Thanks!

Could you try the code:

       build.cmd -pack -ci -configuration Release -prepareMachine /p:Platform=x86

**Comment by wjk** [comment] 2021-01-09 01:35
The CI problems are now fixed. Your advice is appreciated; however, the problem with #1 proved to be transient, as it disappeared after a few merges-from-main. By the way, you should use `-platform x86` rather than the MSBuild syntax, as passing the parameter only to MSBuild will cause problems because it also needs to be specified during dependency resolution (which is done separately beforehand). Thanks!

**Closed as completed by wjk** 2021-01-09 01:35 UTC

**Comment by lindexi** [comment] 2021-01-09 02:09
Thank you

2021-01-09



Lindexi
Microsoft MVP
http://blog.lindexi.com/ 
https://github.com/lindexi/ 
https://lindexi.blog.csdn.net/ 



发件人：William Kent
发送时间：2021-01-09 09:35
主题：Re: [wjk/dotnet-wpf] How about add the github action (#4)
收件人：wjk/dotnet-wpf
抄送：lindexi,Author

The CI problems are now fixed. Your advice is appreciated; however, the problem with #1 proved to be transient, as it disappeared after a few merges-from-main. By the way, you should use -platform x86 rather than the MSBuild syntax, as passing the parameter only to MSBuild will cause problems because it also needs to be specified during dependency resolution (which is done separately beforehand). Thanks!
